Vagrant::Config.run do |config|
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "debian64"

  config.vm.customize do |vm|
    vm.memory_size = 128
    vm.name = "Cucu test"
  end

  config.ssh.max_tries = 100

  config.vm.forward_port("http", 8080, 8080)

  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "../manifests"
    puppet.manifest_file = "site.pp"
    puppet.module_path = "../modules"
    puppet.options = ["--verbose","--environment","local"]
  end
end

